#ifndef SL_BTMESH_PROVISIONEE_CONFIG_H
#define SL_BTMESH_PROVISIONEE_CONFIG_H

#define SL_BTMESH_PROVISIONEE_LOGGING_CFG_VAL 0
#define SL_BTMESH_PROVISIONEE_AUTO_RESET 0
#define SL_BTMESH_PROVISIONEE_AUTO_RESET_DELAY 0
#define SL_BTMESH_PROVISIONEE_AUTO_UNPROV_BEACONING_CFG_VAL 3
#define SL_BTMESH_PROVISIONEE_INIT_PROV_RECORDS_CFG_VAL 0
#define SL_BTMESH_PROVISIONEE_OOB_ENABLE_CFG_VAL 0

#define SL_BTMESH_PROVISIONEE_OOB_PUBLIC_KEY_ENABLE 0
#define SL_BTMESH_PROVISIONEE_AUTH_NO_OOB 1
#define SL_BTMESH_PROVISIONEE_AUTH_STATIC_OOB 0
#define SL_BTMESH_PROVISIONEE_AUTH_INPUT_OOB 0
#define SL_BTMESH_PROVISIONEE_AUTH_OUTPUT_OOB 0

#define SL_BTMESH_PROVISIONEE_OOB_INFO_OTHER 0
#define SL_BTMESH_PROVISIONEE_OOB_INFO_URI 0
#define SL_BTMESH_PROVISIONEE_OOB_INFO_2D_MR_CODE 0
#define SL_BTMESH_PROVISIONEE_OOB_INFO_BAR_CODE 0
#define SL_BTMESH_PROVISIONEE_OOB_INFO_NFC 0
#define SL_BTMESH_PROVISIONEE_OOB_INFO_NUMBER 0
#define SL_BTMESH_PROVISIONEE_OOB_INFO_STRING 0
#define SL_BTMESH_PROVISIONEE_OOB_INFO_ON_BOX 0
#define SL_BTMESH_PROVISIONEE_OOB_INFO_IN_BOX 0
#define SL_BTMESH_PROVISIONEE_OOB_INFO_ON_PAPER 0
#define SL_BTMESH_PROVISIONEE_OOB_INFO_IN_MANUAL 0
#define SL_BTMESH_PROVISIONEE_OOB_INFO_ON_DEVICE 0

#define SL_BTMESH_PROVISIONEE_AUTH_METHODS        \
  ((SL_BTMESH_PROVISIONEE_AUTH_NO_OOB       << 0) \
   | (SL_BTMESH_PROVISIONEE_AUTH_STATIC_OOB << 1) \
   | (SL_BTMESH_PROVISIONEE_AUTH_INPUT_OOB  << 2) \
   | (SL_BTMESH_PROVISIONEE_AUTH_OUTPUT_OOB << 3))

#define SL_BTMESH_PROVISIONEE_OOB_INFO                 \
  ((SL_BTMESH_PROVISIONEE_OOB_INFO_OTHER        << 0)  \
   | (SL_BTMESH_PROVISIONEE_OOB_INFO_URI        << 1)  \
   | (SL_BTMESH_PROVISIONEE_OOB_INFO_2D_MR_CODE << 2)  \
   | (SL_BTMESH_PROVISIONEE_OOB_INFO_BAR_CODE   << 3)  \
   | (SL_BTMESH_PROVISIONEE_OOB_INFO_NFC        << 4)  \
   | (SL_BTMESH_PROVISIONEE_OOB_INFO_NUMBER     << 5)  \
   | (SL_BTMESH_PROVISIONEE_OOB_INFO_STRING     << 6)  \
   | (SL_BTMESH_PROVISIONEE_OOB_INFO_ON_BOX     << 11) \
   | (SL_BTMESH_PROVISIONEE_OOB_INFO_IN_BOX     << 12) \
   | (SL_BTMESH_PROVISIONEE_OOB_INFO_ON_PAPER   << 13) \
   | (SL_BTMESH_PROVISIONEE_OOB_INFO_IN_MANUAL  << 14) \
   | (SL_BTMESH_PROVISIONEE_OOB_INFO_ON_DEVICE  << 15))

#define SL_BTMESH_PROVISIONEE_AUTH_OUTPUT_OOB_SIZE 0
#define SL_BTMESH_PROVISIONEE_AUTH_OUTPUT_OOB_BLINK 0
#define SL_BTMESH_PROVISIONEE_AUTH_OUTPUT_OOB_BEEP 0
#define SL_BTMESH_PROVISIONEE_AUTH_OUTPUT_OOB_VIBRATE 0
#define SL_BTMESH_PROVISIONEE_AUTH_OUTPUT_OOB_NUMERIC 0
#define SL_BTMESH_PROVISIONEE_AUTH_OUTPUT_OOB_ALPHA 0

#define SL_BTMESH_PROVISIONEE_AUTH_OUTPUT_OOB_ACTIONS     \
  ((SL_BTMESH_PROVISIONEE_AUTH_OUTPUT_OOB_BLINK     << 0) \
   | (SL_BTMESH_PROVISIONEE_AUTH_OUTPUT_OOB_BEEP    << 1) \
   | (SL_BTMESH_PROVISIONEE_AUTH_OUTPUT_OOB_VIBRATE << 2) \
   | (SL_BTMESH_PROVISIONEE_AUTH_OUTPUT_OOB_NUMERIC << 3) \
   | (SL_BTMESH_PROVISIONEE_AUTH_OUTPUT_OOB_ALPHA   << 4))

#define SL_BTMESH_PROVISIONEE_AUTH_INPUT_OOB_SIZE 0
#define SL_BTMESH_PROVISIONEE_AUTH_INPUT_OOB_PUSH 0
#define SL_BTMESH_PROVISIONEE_AUTH_INPUT_OOB_TWIST 0
#define SL_BTMESH_PROVISIONEE_AUTH_INPUT_OOB_NUMERIC 0
#define SL_BTMESH_PROVISIONEE_AUTH_INPUT_OOB_ALPHA 0

#define SL_BTMESH_PROVISIONEE_AUTH_INPUT_OOB_ACTIONS     \
  ((SL_BTMESH_PROVISIONEE_AUTH_INPUT_OOB_PUSH      << 0) \
   | (SL_BTMESH_PROVISIONEE_AUTH_INPUT_OOB_TWIST   << 1) \
   | (SL_BTMESH_PROVISIONEE_AUTH_INPUT_OOB_NUMERIC << 2) \
   | (SL_BTMESH_PROVISIONEE_AUTH_INPUT_OOB_ALPHA   << 3))

#endif
