#ifndef SL_RAIL_UTIL_PTI_CONFIG_H
#define SL_RAIL_UTIL_PTI_CONFIG_H

/* BRD4186C: PTI routed to WSTK header PD04/PD05. */
#define SL_RAIL_UTIL_PTI_MODE           SL_RAIL_PTI_MODE_UART
#define SL_RAIL_UTIL_PTI_BAUD_RATE_HZ   1600000

#define SL_RAIL_UTIL_PTI_PERIPHERAL     PTI
#define SL_RAIL_UTIL_PTI_DOUT_PORT        SL_GPIO_PORT_D
#define SL_RAIL_UTIL_PTI_DOUT_PIN         4
#define SL_RAIL_UTIL_PTI_DFRAME_PORT      SL_GPIO_PORT_D
#define SL_RAIL_UTIL_PTI_DFRAME_PIN       5

#endif
