#ifndef SL_RAIL_UTIL_PA_CONFIG_H
#define SL_RAIL_UTIL_PA_CONFIG_H

/* BRD4186C / BRD4002A: radio module PA_VDD is 1.8 V (not 3.3 V). */
#define SL_RAIL_UTIL_PA_POWER_DECI_DBM      100
#define SL_RAIL_UTIL_PA_RAMP_TIME_US        10
#define SL_RAIL_UTIL_PA_VOLTAGE_MV          1800
#define SL_RAIL_UTIL_PA_SELECTION_2P4GHZ    RAIL_TX_POWER_MODE_2P4GIG_HIGHEST
#define SL_RAIL_UTIL_PA_SELECTION_SUBGHZ    RAIL_TX_POWER_MODE_NONE
#define SL_RAIL_UTIL_PA_CURVE_HEADER        "pa_curves_efr32.h"
#define SL_RAIL_UTIL_PA_CURVE_TYPES         "pa_curve_types_efr32.h"
#define SL_RAIL_UTIL_PA_CALIBRATION_ENABLE  1

#endif
