#ifndef SL_RAIL_UTIL_SEQUENCER_CONFIG_H
#define SL_RAIL_UTIL_SEQUENCER_CONFIG_H

#define SL_RAIL_UTIL_SEQUENCER_RUNTIME_IMAGE_SELECTION 0

/* EFR32MG24B220 = +20 dBm PA (B210 would use PA_10_DBM). */
#define SL_RAIL_UTIL_SEQUENCER_IMAGE RAIL_SEQ_IMAGE_PA_20_DBM

#endif
