#ifndef SL_SLEEPTIMER_CONFIG_H
#define SL_SLEEPTIMER_CONFIG_H

#define SL_SLEEPTIMER_PERIPHERAL_DEFAULT 0
#define SL_SLEEPTIMER_PERIPHERAL_RTCC    1
#define SL_SLEEPTIMER_PERIPHERAL_PRORTC  2
#define SL_SLEEPTIMER_PERIPHERAL_RTC     3
#define SL_SLEEPTIMER_PERIPHERAL_SYSRTC  4
#define SL_SLEEPTIMER_PERIPHERAL_BURTC   5
#define SL_SLEEPTIMER_PERIPHERAL_WTIMER  6
#define SL_SLEEPTIMER_PERIPHERAL_TIMER   7

/* Read SYSRTC counter (same 32.768 kHz source as embassy time driver). */
#define SL_SLEEPTIMER_PERIPHERAL  SL_SLEEPTIMER_PERIPHERAL_SYSRTC

#define SL_SLEEPTIMER_TIMER_INSTANCE  0
#define SL_SLEEPTIMER_WALLCLOCK_CONFIG 0
#define SL_SLEEPTIMER_FREQ_DIVIDER      1
#define SL_SLEEPTIMER_PRORTC_HAL_OWNS_IRQ_HANDLER 0
#define SL_SLEEPTIMER_DEBUGRUN          0

#endif
