[package]
name = "silabs-pac"
version = "0.1.0"
edition = "2021"

[dependencies]
critical-section = { version = "1.0", optional = true }
cortex-m = "0.7.7"
cortex-m-rt = { version = "0.7.5", optional = true }
vcell = "0.1.3"
defmt = { version = "1.0.1", optional = true }

[features]
default = ["critical-section"]
rt = ["cortex-m-rt/device"]
defmt = ["dep:defmt"]
